//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceContractErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceContractErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Errors.ResourceContractErrors", typeof(ResourceContractErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception type {0} doesn&apos;t have a constructor with (string, Error) parameters..
        /// </summary>
        internal static string ERROR_CONTRACT_CANTINSTANTIATEEXCEPTION {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_CANTINSTANTIATEEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General contract error without specific information..
        /// </summary>
        internal static string ERROR_CONTRACT_GENERAL {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values should not be equals, comparing &apos;{0}&apos; with &apos;{1}&apos;. .
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFEQUAL {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFEQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be true..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFFALSE {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFFALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not part of the enum type &apos;{1}&apos;..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFINVALIDENUMVALUE {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFINVALIDENUMVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values should be equals, comparing &apos;{0}&apos; with &apos;{1}&apos;..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFNOTEQUAL {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFNOTEQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has a value &apos;{1}&apos; but should be null..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFNOTNULL {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFNOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; should be type &apos;{1}&apos;..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFNOTTYPE {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFNOTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should not be null..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFNULL {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string should not be null, empty or only containing white spaces..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFSTRINGISNULLORWHITESPACE {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFSTRINGISNULLORWHITESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be false..
        /// </summary>
        internal static string ERROR_CONTRACT_THROWIFTRUE {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_THROWIFTRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown contract error..
        /// </summary>
        internal static string ERROR_CONTRACT_UNKNOWN {
            get {
                return ResourceManager.GetString("ERROR_CONTRACT_UNKNOWN", resourceCulture);
            }
        }
    }
}
